name: Monthly Commentary

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 1 * *"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate monthly commentary
        run: python -m src.cli --month auto --markets us,au --outputs md,xlsx
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: monthly-commentary-${{ github.run_id }}
          path: reports/
      - name: Prepare Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4

  email:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Email notifications disabled
        run: echo "Email notifications are disabled until SMTP secrets are provided."
